// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoUrna.Data;

namespace ProjetoUrna.Migrations
{
    [DbContext(typeof(ProjetoUrnaContext))]
    [Migration("20210516140552_entities")]
    partial class entities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoUrna.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Partido");
                });

            modelBuilder.Entity("ProjetoUrna.Models.Presidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("NomePresidente");

                    b.Property<string>("NomeVice");

                    b.Property<int?>("PartidoId");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Presidente");
                });

            modelBuilder.Entity("ProjetoUrna.Models.TotalVoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataVoto");

                    b.Property<int?>("PresidenteId");

                    b.Property<int>("Situacao");

                    b.Property<int>("Soma");

                    b.HasKey("Id");

                    b.HasIndex("PresidenteId");

                    b.ToTable("TotalVoto");
                });

            modelBuilder.Entity("ProjetoUrna.Models.Presidente", b =>
                {
                    b.HasOne("ProjetoUrna.Models.Partido", "Partido")
                        .WithMany("Presidente")
                        .HasForeignKey("PartidoId");
                });

            modelBuilder.Entity("ProjetoUrna.Models.TotalVoto", b =>
                {
                    b.HasOne("ProjetoUrna.Models.Presidente", "Presidente")
                        .WithMany("Votos")
                        .HasForeignKey("PresidenteId");
                });
#pragma warning restore 612, 618
        }
    }
}
